import { Inter } from 'next/font/google'
import './globals.css'
import SideBar from './components/Sidebar'
import TopBar from './components/Topbar'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <div className='flex flex-row h-screen w-screen overflow-hidden'>
            <SideBar/>
            <div className='w-screen overflow-y-auto ml-6 pr-6'>
              <TopBar/>
              <div className='p-4'>
                {children}
              </div>
            </div>
          </div>
      </body>
    </html>
  )
}
